default: &default
  adapter: postgresql
  encoding: unicode
  username: priya
  pool: 5

development:
  <<: *default
  database: zc_wallet_development

test:
  <<: *default
  database: zc_wallet_test

production:
  <<: *default
  database: zc_wallet_production
  password: <%= ENV['DEMOCRARY_DATABASE_PASSWORD'] %>


